### ISSUE TITLE
Can't install latest version via opam

### ISSUE THREAD

**Issue by yminsky** [janestreet/shexp#1]
This is just after the latest upgrade...

    #=== ERROR while installing shexp.114.08+09 ===================================#
    # opam-version 1.2.2
    # os           darwin
    # command      make
    # path         /Users/yminsky/.opam/4.03.0/build/shexp.114.08+09
    # compiler     4.03.0
    # exit-code    2
    # env-file     /Users/yminsky/.opam/4.03.0/build/shexp.114.08+09/shexp-32221-543ebd.env
    # stdout-file  /Users/yminsky/.opam/4.03.0/build/shexp.114.08+09/shexp-32221-543ebd.out
    # stderr-file  /Users/yminsky/.opam/4.03.0/build/shexp.114.08+09/shexp-32221-543ebd.err
    ### stdout ###
    # ./setup.exe -build
    # ocamlfind ocamlopt unix.cmxa -I /Users/yminsky/.opam/4.03.0/lib/ocamlbuild /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
    # + ocamlfind ocamlopt unix.cmxa -I /Users/yminsky/.opam/4.03.0/lib/ocamlbuild /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
    # File "myocamlbuild.ml", line 5, characters 12-42:
    # Error: Unbound module Jane_street_ocamlbuild_goodies
    # Command exited with code 2.
    ### stderr ###
    # [...]
    # W: Cannot find source file matching module 'shexp_sexp' in library shexp_sexp.
    # W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
    # W: Cannot find source file matching module 'shexp_bigstring_io' in library shexp_bigstring_io.
    # W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
    # W: Cannot find source file matching module 'shexp_bigstring' in library shexp_bigstring.
    # W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
    # W: Cannot find source file matching module 'sexp0' in library sexp0.
    # W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
    # E: Failure("Command ''/Users/yminsky/.opam/4.03.0/bin/ocamlbuild' sexp0/src/sexp0.cma sexp0/src/sexp0.cmxa sexp0/src/sexp0.a sexp0/src/sexp0.cmxs bigstring-lib/src/libshexp_bigstring_stubs.a bigstring-lib/src/dllshexp_bigstring_stubs.so bigstring-lib/src/shexp_bigstring.cma bigstring-lib/src/shexp_bigstring.cmxa bigstring-lib/src/shexp_bigstring.a bigstring-lib/src/shexp_bigstring.cmxs bigstring-io-lib/src/libshexp_bigstring_io_stubs.a bigstring-io-lib/src/dllshexp_bigstring_io_stubs.so bigstring-io-lib/src/shexp_bigstring_io.cma bigstring-io-lib/src/shexp_bigstring_io.cmxa bigstring-io-lib/src/shexp_bigstring_io.a bigstring-io-lib/src/shexp_bigstring_io.cmxs sexp-lib/src/shexp_sexp.cma sexp-lib/src/shexp_sexp.cmxa sexp-lib/src/shexp_sexp.a sexp-lib/src/shexp_sexp.cmxs posixat-lib/src/libshexp_posixat_stubs.a posixat-lib/src/dllshexp_posixat_stubs.so posixat-lib/src/shexp_posixat.cma posixat-lib/src/shexp_posixat.cmxa posixat-lib/src/shexp_posixat.a posixat-lib/src/shexp_posixat.cmxs spawn-lib/src/libshexp_spawn_stubs.a spawn-lib/src/dllshexp_spawn_stubs.so spawn-lib/src/shexp_spawn.cma spawn-lib/src/shexp_spawn.cmxa spawn-lib/src/shexp_spawn.a spawn-lib/src/shexp_spawn.cmxs process-lib/src/shexp_process.cma process-lib/src/shexp_process.cmxa process-lib/src/shexp_process.a process-lib/src/shexp_process.cmxs -use-ocamlfind -tag debug' terminated with error code 10")
    # make: *** [build] Error 1

**Comment by diml** [comment]
Same as https://github.com/janestreet/opam-repository/issues/1#issuecomment-243340155, I just pushed a upper version constraint for oasis
