### ISSUE TITLE
Processor-specific limitations

### ISSUE THREAD

**Issue by rboissy** [janestreet/shexp#10]
Hi,

Ocaml is supported on the RISC-V ISA.  Are there processor-specific limitations to shexp that would preclude its use on a Linux distribution that supports Ocaml, e.g., OpenMandriva:

http://abf-downloads.openmandriva.org/cooker/repository/riscv64/main/release/

Thanks for your work on this library and your help with this issue.

Robert

P.S. Also, what about AArch64 (64-bit ARM)?

**Comment by jeremiedimino** [comment]
Hi Robert,

There is no limitation I can think of. Shexp is a standard OCaml project. If you are aware of shexp not working on some operating systems/hardware where OCaml is supported, please let us know. In the meantime, I'm closing this issue.

Thanks
