### ISSUE TITLE
Not available in opam?

### ISSUE THREAD

**Issue by russelldmatt** [janestreet/shexp#3]
Related issue.  I don't see shexp available in opam, although the shexp.opam (and Ron's output in issue #1) makes me think it is available.

I thought it was because my compiler was too old (4.02.3), but even after upgrading to 4.03.0, `$ opam list -A | grep -i shexp` returns nothing.  Also, searching on http://opam.ocaml.org/packages/ for shexp returns no results.  What am I doing wrong?

**Comment by yminsky** [comment]
You need to use the bleeding edge opam repo, since the new set of packages
(which include shexp) have not yet been integrated into the main opam repo.

Here's the repo:

https://github.com/janestreet/opam-repository

So you need to type something like

opam repo add js-bleeding https://github.com/janestreet/opam-repository

and then try the install.

y

**Comment by russelldmatt** [comment]
Thanks for the response, but that command is failing for me.  Maybe we need to add a urls.txt in the repo?

> $ opam repo add js-bleeding https://github.com/janestreet/opam-repository
> [js-bleeding] Downloading https://github.com/janestreet/opam-repository/urls.txt
> [ERROR] curl: code 404 while downloading https://github.com/janestreet/opam-repository/urls.txt
> Updating ~/.opam/repo/compiler-index ...
> Updating ~/.opam/compilers/ ...
> Updating ~/.opam/repo/package-index ...
> Updating ~/.opam/packages/ ...
> \# opam-version    1.2.0
> \# os              darwin
> curl: code 404 while downloading https://github.com/janestreet/opam-repository/urls.txt
> EXIT STATUS: 1

**Comment by yminsky** [comment]
Try this instead:

opam repo add js-bleeding git@github.com:janestreet/opam-repository.git

**Comment by russelldmatt** [comment]
Still no :/

> $ opam repo add js-bleeding git@github.com:janestreet/opam-repository.git
> [js-bleeding] Fetching git@github.com:janestreet/opam-repository.git
> Updating ~/.opam/repo/compiler-index ...
> Updating ~/.opam/compilers/ ...
> Updating ~/.opam/repo/package-index ...
> Updating ~/.opam/packages/ ...
> \# opam-version 1.2.0
> \# os           darwin
> \# command      git fetch origin +HEAD:refs/remotes/opam-ref
> \# path         /Users/mrussell/.opam/repo/js-bleeding
> \# exit-code    128
> \# env-file     /Users/mrussell/.opam/log/log-63487-ffb3fd.env
> \# stdout-file  /Users/mrussell/.opam/log/log-63487-ffb3fd.out
> \# stderr-file  /Users/mrussell/.opam/log/log-63487-ffb3fd.err
> \### stderr ###
> \# Permission denied (publickey).
> \# fatal: Could not read from remote repository.
> \#
> \# Please make sure you have the correct access rights
> \# and the repository exists.
> 
> EXIT STATUS: 1

**Comment by yminsky** [comment]
Hmm. Maybe that repo isn't readable by everyone. I just added you
explicitly with read-access. Try it again.

**Comment by samoht** [comment]
to get read-access, use https://github.com/janestreet/opam-repository.git

**Comment by russelldmatt** [comment]
Yep, that worked.  Thanks to both of you for the help!
