### ISSUE TITLE
Any plan to integrate shexp into the main opam repo?

### ISSUE THREAD

**Issue by liweijian** [janestreet/shexp#4]
I have read the related post [Not available in opam?](https://github.com/janestreet/shexp/issues/3) before.

In order to install shexp, I add a new repo a long time ago

```
$ opam repo add janestreet git://github.com/janestreet/opam-repository.git
```

But I got some conflict with ipaddr, details in [ipaddr 2.7.1 opam install failed](https://github.com/mirage/ocaml-ipaddr/issues/62).

I have to remove that repo to install ipaddr

```
opam repo remove janestreet
```

I was wondering if there's any plan to integrate shexp into the main opam repo?

**Comment by diml** [comment]
Yeah, we'll release it as part of the next stable of Jane Street packages. Given the number of packages, it's much easier for us to release everything together

**Comment by diml** [comment]
Shexp is now in opam
