### ISSUE TITLE
Type of run

### ISSUE THREAD

**Issue by grayswandyr** [janestreet/shexp#7]
Hi,
perhaps there is a good reason for this, but I wonder why the type of `run` is `string -> string list -> unit Shexp_process.t` and not `string list -> unit Shexp_process.t` with the convention that the head of the list contains the program to be run (ditto for fro other variants of `run` and `spawn` of course)? The latter solution makes it far easier for the programmer to toy with a command, e.g. preprend conditionnally a call to `time` in front of a command.

**Comment by grayswandyr** [comment]
EDIT: sorry, I add thought of something that seems even more convenient but forgot to ask about it: taking directly a format directive as a single parameter. Meaning one could write something like:
```
run "grep -A %d %s %s" 3 pattern filename
```
for instance. I tend to think this really goes well with shell s(h)cripting.

**Comment by diml** [comment]
For the first question, it seemed more natural to me to write the API this way, given the the program is mandatory. I admit that it doesn't seem convenient to wrap a command with `time`. Another solution would be to provide `Process.time : 'a t -> (Process.Times.t * 'a) t` that would work for both external commands and internal code.

> `run {|grep -A %d '%s' "%s"|} 3 pattern filename`

That requires parsing the command and interpreting the quotes, etc... right?

**Comment by grayswandyr** [comment]
More generally than `time`, I tend to think that one may manipulate a command line in many ways, which makes the dissymmetry between the first argument and others problematic. So I tend to think there should be a single argument to `run`.

So, if you accept this consideration, then you have plenty of possibilities, among which a single string list (as in my first post) or, straight out, a single string. In the latter case, I would go as far as using a format string (as in my second post) because I think it goes very well with the spirit of shell scripting in OCaml: quick but no too dirty :-)  I would not interpret quotes at all, just split on blanks, and considering the first substring as the program. So (using `call` as a name for this new command, to keep `run` as before):
```
call {|grep -A %d '%s' "%s"|} 3 pattern filename
```
would have the same meaning as:
```
run "grep" [ "-A"; "3"; "'pattern'"; "\"filename\"" ]
```
The `{| |}` notation is great because it alleviates the user from dealing with quote escaping.

Of course, this `call` does require parsing to split on blanks.

BTW, inspired by Shcaml, a function `backquote fmt args` that would the same thing as `eval (call fmt args |- read_all)` would be very useful too, I think, as it's such a common situation.

Finally, I think indeed functions such as `time` and, even more importantly `timeout`, would be very great in practice.

**Comment by diml** [comment]
These requests look valid, but TBH I don't have much time to work on shexp. Basically, I initially wrote shexp as I wanted a portable shell for generating Makefiles from jenga. But then Jbuilder superseded this idea.

A PR would be welcome though :)

**Comment by grayswandyr** [comment]
OK I'll see into this. 
One question though: do you expect the current API to change, or should I introduce new function names to avoid changing the old API?

**Comment by diml** [comment]
New function names please, we have some programs using shexp

**Comment by jeremiedimino** [comment]
@grayswandyr I'm closing this as I believe there is nothing more to do here. Feel free to re-open if there is still something to do. (I'm just going over my list of open issues, I didn't re-read the whole conversation)
