### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by shinzui** [janestreet/shexp#9]
`shexp` does not install on OCaml 4.0.7 with new versions of `Base`.

**Comment by diml** [comment]
The version that's released in opam hasn't been tested with 4.07. We are planning to do a new major release of all Jane Street packages in the coming weeks.

**Comment by struktured** [comment]
@diml any updated estimate on this upgrade?

**Comment by diml** [comment]
Soon hopefully, the release got blocked unexpectedly due to compatibility problems caused by the bigarray module moving to the stdlib, but these issues are almost fixed.

**Comment by xclerc** [comment]
Fixed in release v0.12.0.
